# Generated by Django 5.0 on 2023-12-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='task',
            field=models.TextField(max_length=100),
        ),
    ]
