# Generated by Django 5.0 on 2023-12-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_rename_task_taskmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name_plural': 'Tasks'},
        ),
    ]
