# Generated by Django 5.0 on 2023-12-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_taskmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
